# Generated by Django 5.1.4 on 2025-01-28 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('itens', models.ManyToManyField(to='pedidos.itemcarrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em preparo', 'Em Preparo'), ('entregue', 'Entregue')], default='pendente', max_length=20)),
                ('endereco_envio', models.TextField()),
                ('metodo_pagamento', models.CharField(choices=[('cartao', 'Cartão'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('carrinho', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.carrinho')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
