# Generated by Django 5.1.4 on 2025-02-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrinho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.carrinho'),
        ),
    ]
