# Generated by Django 5.1.4 on 2025-03-21 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_itempedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
