# Generated by Django 5.1.4 on 2025-03-09 18:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='nome_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.produto'),
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 18, 57, 17, 291608)),
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
