# Generated by Django 5.1.4 on 2025-03-09 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_vendas_nome_produto_remove_vendas_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 19, 47, 18, 37794)),
        ),
    ]
