# Generated by Django 5.1.4 on 2025-03-12 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_vendas_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendas',
            options={'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 12, 22, 53, 42, 592862)),
        ),
    ]
