# Generated by Django 5.1.4 on 2025-02-20 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rua',
        ),
        migrations.CreateModel(
            name='EnderecoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
