# Generated by Django 5.1.4 on 2025-01-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.FloatField()),
                ('ingrediente', models.TextField()),
                ('categoria', models.CharField(choices=[('Pizza', 'Pizza'), ('Bebida', 'Bebida')], max_length=50)),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
            },
        ),
    ]
